/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./About.module.css";

type AboutProps = {
  content: string;
};

const About: React.FC<AboutProps> = ({ content }) => {
  return (
    <section className={styles.about}>
      <h2 className={styles.aboutTitle}>A Little Bit About Me</h2>
      <p className={styles.aboutContent}>{content}</p>
      <a href="#contact" className={styles.contactCta}>
        Contact Me
      </a>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e77d9146b651fc26670c7be40125e243381d85ed57cf2a6e466c3c219fc94592?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd"
        alt="About me illustration"
        className={styles.aboutImage}
      />
    </section>
  );
};

export default About;
