/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./Header.module.css";

type HeaderProps = {
  menuItems: string[];
};

const Header: React.FC<HeaderProps> = ({ menuItems }) => {
  return (
    <header className={styles.header}>
      <nav className={styles.navigation}>
        {menuItems.map((item, index) => (
          <a
            key={index}
            href={`#${item.toLowerCase()}`}
            className={styles.navItem}
          >
            {item}
          </a>
        ))}
      </nav>
    </header>
  );
};

export default Header;
