/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./Hero.module.css";

type HeroProps = {
  greeting: string;
  name: string;
  title: string;
};

const Hero: React.FC<HeroProps> = ({ greeting, name, title }) => {
  return (
    <section className={styles.hero}>
      <div className={styles.heroContent}>
        <span className={styles.greeting}>{greeting}</span>
        <h1 className={styles.title}>
          I'm {name}, <br />
          {title}
        </h1>
        <div className={styles.ctaContainer}>
          <a href="#work" className={styles.primaryCta}>
            View My Work
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c1a90be31339364e460a3af1aac7d14d3278d8ba4494173886c8290dbafeb3b6?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd"
              alt=""
              className={styles.ctaIcon}
            />
          </a>
          <a href="#contact" className={styles.secondaryCta}>
            Contact Me
          </a>
        </div>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/eccf7cf8af0328a2c3c41029c8ee4bdc563ce58124b1789ba9c7e4b8698bcb07?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd"
        alt="Hero illustration"
        className={styles.heroImage}
      />
    </section>
  );
};

export default Hero;
