/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import WorkCard from "./WorkCard";
import Testimonial from "./Testimonial";
import About from "./About";
import Contact from "./Contact";
import styles from "./Portfolio.module.css";

const Portfolio: React.FC = () => {
  const menuItems = ["Home", "Work", "Testimonials", "About"];
  const workProjects = [
    {
      title: "Sheepify States",
      description:
        "Designed some empty state screens in kawaii style for the popular sheepify app",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4c7ce611114fd007698405762699a0e75e5e58df51dbbc82a5bfd20251b3bcb9?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd",
    },
    {
      title: "HoneyBunny",
      description:
        "A colorful dashboard to manage your fictional projects and team, all in a single place.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/428484ade9fdf6c1bf888ec229a949bc52b0b75abb648788c51d6524bbe0aac5?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd",
    },
    {
      title: "Memrise Redesign",
      description:
        "I redesigned the popular language learning app memrise in kawaii style to make it more cute.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/96d1924ec752486460880d9e3d972639bf24a5c4f1b5197410bc52604b79e13e?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd",
    },
  ];
  const testimonials = [
    {
      quote:
        "I had grown a little bit disappointed when I realized that my work would not be taking me in any new, creative design directions. Thankfully, I found Salman Khan and his creativity that goes above and beyond, proving to be exactly what I needed to take.",
      author: "Aika Chan",
      avatarSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/741319a7b9c231eda6d93ffbd651ccc88fb5a3678159b459684c552174a066fa?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd",
    },
    {
      quote:
        "Salman Khan is the best designer that I have ever worked with. He is seriously what you would call 'creative': he innovatively solves all sorts of problems and always delivers both prompt and high quality work. I can't recommend him enough!",
      author: "Arakan Chan",
      avatarSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/608910dbbdbf2c7e63f0795fc229185cabde49b08c50c9b6b084c2d7ac9b689c?placeholderIfAbsent=true&apiKey=3b2a0042ca5b469d94ce21876bd60fcd",
    },
  ];
  const aboutContent = `I am Salman Khan from Lucknow, India. I am working in an Indian Startup as a User Experience Designer for the past two years. I got featured various times on many big and small marketplaces, portfolio websites and blogs. I also received some awards and recognitions from some of the big and small award companies. Besides designing, I like to watch anime, read books and solve sudoku.`;

  return (
    <div className={styles.portfolio}>
      <Header menuItems={menuItems} />
      <main>
        <Hero
          greeting="👋 Hello All"
          name="Salman Khan"
          title="A Creative Designer and Storyteller"
        />
        <section className={styles.workSection}>
          <h2 className={styles.sectionTitle}>My Recent Work</h2>
          {workProjects.map((project, index) => (
            <WorkCard key={index} {...project} />
          ))}
        </section>
        <section className={styles.testimonialSection}>
          <h2 className={styles.sectionTitle}>Some Generous Words</h2>
          <p className={styles.testimonialSubtitle}>
            Some of my favorite testimonials from my clients
          </p>
          <div className={styles.testimonialGrid}>
            {testimonials.map((testimonial, index) => (
              <Testimonial key={index} {...testimonial} />
            ))}
          </div>
        </section>
        <About content={aboutContent} />
        <Contact />
      </main>
    </div>
  );
};

export default Portfolio;
