/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./Testimonial.module.css";

type TestimonialProps = {
  quote: string;
  author: string;
  avatarSrc: string;
};

const Testimonial: React.FC<TestimonialProps> = ({
  quote,
  author,
  avatarSrc,
}) => {
  return (
    <figure className={styles.testimonial}>
      <img
        src={avatarSrc}
        alt={`${author}'s avatar`}
        className={styles.avatar}
      />
      <blockquote className={styles.quote}>{quote}</blockquote>
      <figcaption className={styles.author}>{author}</figcaption>
    </figure>
  );
};

export default Testimonial;
