/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./WorkCard.module.css";

type WorkCardProps = {
  title: string;
  description: string;
  imageSrc: string;
};

const WorkCard: React.FC<WorkCardProps> = ({
  title,
  description,
  imageSrc,
}) => {
  return (
    <article className={styles.workCard}>
      <div className={styles.workContent}>
        <h3 className={styles.workTitle}>{title}</h3>
        <p className={styles.workDescription}>{description}</p>
        <a href="#" className={styles.caseStudyLink}>
          View Case Study
        </a>
      </div>
      <img
        src={imageSrc}
        alt={`${title} project screenshot`}
        className={styles.workImage}
      />
    </article>
  );
};

export default WorkCard;
